### ISSUE TITLE
这个工作很棒，有几个小问题

### ISSUE THREAD

**Issue by brightmart** [airaria/TextBrewer#1]
这个工作很及时，一下子将蒸馏的复杂度和可操作性降低下来了，很有意义。

刚开始了解这个项目，有几点反馈：

1. 快速开始里面：“同时匹配教师的第8层和学生的第2层”
能否说明一下，这是什么意思，也就是说为什么要用教师的第8层和学生的第2层，而不是其他层之间的匹配。

2. 数据增强有效的提升了最终的效果，那么能否也列一下只有蒸馏而没有采用数据增强的效果，这样能看到单纯的蒸馏的效果。

3. 更为关键的对比是，直接训练和蒸馏的效果的对比能否贴出来，如直接预训练过的T3和蒸馏过的T3在CMRC 2018上的对比，即希望能看到蒸馏相对于非蒸馏的增值部分。 

4. 中文任务上，LCQMC这个任务模型的区分能力是不够的。如我们的测评中最好的模型比bert-base在测试集上只提升了0.4个点，就会导致比较一般的模型也还有不错的分数。那么能否在其他区分性大的任务上也测一测蒸馏的效果。

**Comment by airaria** [comment]
你好，感觉你的关注！

1. 快速开始里的例子里用第八层和第二层只是出于演示intermeidate_matches这个选项目的，没有其他意义。具体在实际任务中怎么设置，可以参看mnli和cmrc2018的example。

2 & 3:  数据增强的ablation studies已有一些整理好的结果，如下：
英文数据集：
![en_da](https://user-images.githubusercontent.com/4355449/75871541-ac9ed200-5e47-11ea-82ab-6e2871efb24b.png)
中文数据集：
![zh_da](https://user-images.githubusercontent.com/4355449/75871560-b45e7680-5e47-11ea-9222-a7b867fa193e.png)
其他结果，以及如直接训练等，我们之后会在README.md中陆续更新。

4. 是的，从蒸馏结果也可以看出 LCQMC这个任务并不是太难。我们会考察其他较具有难度的分类任务。

**Comment by ymcui** [comment]
如有其它问题可随时reopen。
