### ISSUE TITLE
pre-trained student weights

### ISSUE THREAD

**Issue by roymiles** [airaria/TextBrewer#101]
Hi
Thanks for releasing this project! You mentioned it is beneficial to initialize the student with pre-trained weights. Do you provide these weights by any chance? Specifically for the models used for the SQuAD task (L3 etc)

At the moment we are just copying the pre-trained weights from base bert into the first few 3 layers, but I am unsure if this is the best/recommended way of doing it.

Thanks

**Comment by airaria** [comment]
> Hi Thanks for releasing this project! You mentioned it is beneficial to initialize the student with pre-trained weights. Do you provide these weights by any chance? Specifically for the models used for the SQuAD task (L3 etc)
> 
> At the moment we are just copying the pre-trained weights from base bert into the first few 3 layers, but I am unsure if this is the best/recommended way of doing it.
> 
> Thanks

We initialized the student with the first 3 layers of BERT, same as what you did.
It is the recommended way (I have experimented other schemes and I don't know if there are other simple and better ways)
