### ISSUE TITLE
在VisionTransformer

### ISSUE THREAD

**Issue by zym1599** [airaria/TextBrewer#110]
您好，非常感谢开源。请教您，在Vision-Transformer尝试中加载数据后报错，要求输入两个参数，却输入了三个。随后补充报错，感谢！希望百忙中给予一些解答，谢谢您！
TypeError: forward() takes 2 positional arguments but 3 were given
![image](https://user-images.githubusercontent.com/42165621/202953982-94fe04c2-b01c-4b9f-9751-e98468863c58.png)

![捕获2222](https://user-images.githubusercontent.com/42165621/202977149-97d11815-8563-4a09-842d-07394003dd50.PNG)

**Comment by airaria** [comment]
可否提供一下adaptor的定义，和你的Vision-Transformer代码？

> 您好，非常感谢开源。请教您，在Vision-Transformer尝试中加载数据后报错，要求输入两个参数，却输入了三个。随后补充报错，感谢！希望百忙中给予一些解答，谢谢您！ TypeError: forward() takes 2 positional arguments but 3 were given ![image](https://user-images.githubusercontent.com/42165621/202953982-94fe04c2-b01c-4b9f-9751-e98468863c58.png)
> 
> ![捕获2222](https://user-images.githubusercontent.com/42165621/202977149-97d11815-8563-4a09-842d-07394003dd50.PNG)

**Comment by zym1599** [comment]
> 您好，非常感谢开源。请教您，在Vision-Transformer尝试中加载数据后报错，要求输入两个参数，却输入了三个。随后补充报错，感谢！希望百忙中给予一些解答，谢谢您！TypeError： forward（） 需要 2 个位置参数，但给出了 3 个 ![图像](https://user-images.githubusercontent.com/42165621/202953982-94fe04c2-b01c-4b9f-9751-e98468863c58.png)
> 
> ![捕获2222](https://user-images.githubusercontent.com/42165621/202977149-97d11815-8563-4a09-842d-07394003dd50.PNG)

[dilstill.txt](https://github.com/airaria/TextBrewer/files/10055914/dilstill.txt)
[vit_model.txt](https://github.com/airaria/TextBrewer/files/10055917/vit_model.txt)


> 可否提供一下adaptor的定义，和你的Vision-Transformer代码？
> 
> > 您好，非常感谢开源。请教您，在Vision-Transformer尝试中加载数据后报错，要求输入两个参数，却输入了三个。随后补充报错，感谢！希望百忙中给予一些解答，谢谢您！ 类型错误： forward（） 需要 2 个位置参数，但给出了 3 个![图像](https://user-images.githubusercontent.com/42165621/202953982-94fe04c2-b01c-4b9f-9751-e98468863c58.png)
> > ![捕获2222](https://user-images.githubusercontent.com/42165621/202977149-97d11815-8563-4a09-842d-07394003dd50.PNG)

万分感谢您的指教，已附代码。
[vit_model.txt](https://github.com/airaria/TextBrewer/files/10055930/vit_model.txt)
[dilstill.txt](https://github.com/airaria/TextBrewer/files/10055933/dilstill.txt)

**Comment by airaria** [comment]
能否说明下每个 batch中有多少个元素，元素类型分别是什么？
