### ISSUE TITLE
不同维度蒸馏有对应的例子吗，从768降到256

### ISSUE THREAD

**Issue by weidalan** [airaria/TextBrewer#113]

**Comment by airaria** [comment]
CMRC 2018例子下的un_cmrc2018_distill_T4tiny.sh从768降到312:
https://github.com/airaria/TextBrewer/tree/master/examples/cmrc2018_example/run_cmrc2018_distill_T4tiny.sh

**Comment by weidalan** [comment]
> CMRC 2018例子下的un_cmrc2018_distill_T4tiny.sh从768降到312: https://github.com/airaria/TextBrewer/tree/master/examples/cmrc2018_example/run_cmrc2018_distill_T4tiny.sh

感谢~
