### ISSUE TITLE
老师，您好，请问有多任务多教师的蒸馏的demo吗？

### ISSUE THREAD

**Issue by lean-wang** [airaria/TextBrewer#115]

**Comment by ymcui** [comment]
https://github.com/airaria/TextBrewer/tree/master/examples/mnli_example

**Comment by lean-wang** [comment]
> https://github.com/airaria/TextBrewer/tree/master/examples/mnli_example

大佬您好，这个只是多教师，没有多任务的

**Comment by ymcui** [comment]
多任务的就麻烦自己改一下吧
