### ISSUE TITLE
请教MultiTeacherDistiller模型

### ISSUE THREAD

**Issue by sunyilgdx** [airaria/TextBrewer#13]
感谢您的成果分享！麻烦问一下有没有MutiTeacherDistiller模型的相关实现细节的介绍，我看论文里没太提到，代码里像是用了多个教师模型的损失的平均，有没有相关的研究论文？感谢！

**Comment by airaria** [comment]
你好！
关于多教师蒸馏，主要参考：
[Improving Multi-Task Deep Neural Networks via Knowledge Distillation for Natural Language Understanding](https://arxiv.org/abs/1904.09482)

我的调研也不尽全面，如果有所遗漏，还望包涵！

**Comment by sunyilgdx** [comment]
谢谢，正在看，期待更多工作！
