### ISSUE TITLE
AttributeError: type object 'BertConfig' has no attribute 'pretrained_config_archive_map'

### ISSUE THREAD

**Issue by tcclks** [airaria/TextBrewer#16]
bash run_conll2003_train.sh:

issue:
(tuple(conf.pretrained_config_archive_map.keys()) for conf in (BertConfig, RobertaConfig, DistilBertConfig)),
AttributeError: type object 'BertConfig' has no attribute 'pretrained_config_archive_map'

downgrade the transformers version(2.0.0) solves the issue,but come with more issues.

eg:
1.ImportError: cannot import name 'get_linear_schedule_with_warmup'
2.from transformers import RobertaConfig, RobertaForTokenClassification, RobertaTokenizer
ImportError: cannot import name 'RobertaForTokenClassification'

it needs the transformers version(>2.0.0).(pip3 install git+https://github.com/huggingface/transformers.git --upgrade)

So,how does it work?

Thanks!

**Comment by airaria** [comment]
Have you tried Transformers 2.2.1?
Thank you for reminding me, I'll add this to the README
