### ISSUE TITLE
关于不同模型之间的蒸馏问题

### ISSUE THREAD

**Issue by renxingkai** [airaria/TextBrewer#19]
想问下是不是还不支持类似把Roberta蒸馏到electra这样的方式，只支持同源预训练模型之间的蒸馏(至少词表大小一致？)？我尝试了，发现词表大小不匹配，导致报错

**Comment by airaria** [comment]
你蒸馏什么任务？文本分类应该没有问题。
不同的词表主要影响输入的长度，比如同一段文本，经BERT分词后长度30，而经RoBERTa分词后长度25。这会导致：
1. 如果是序列标注任务或阅读理解任务，会直接无法匹配，因为ground-truth的位置都变了
2. 部分中间隐层loss无法计算，比如hidden_mse，因为计算过程中需要匹配两个长度一样的矩阵。不过有的loss还是可以算的，比如fsp。
综上，当两个模型词表不同时，目前只可以蒸馏分类任务，并且使用的intermediate losses的种类受限。
不过因为目前的train接口里只接受一个dataloader，所以需要在一个dataloader中同时为两个模型提供对应的batch，这点需要留意下。

希望我的解答对您有所帮助。

**Comment by renxingkai** [comment]
嗯嗯，谢谢您的解答，我做的就是文本分类任务，看error确实是中间层loss维度不匹配报错了，已修改其他蒸馏方式，再次感谢您的回答
