### ISSUE TITLE
可以用于NMT的任务中吗？

### ISSUE THREAD

**Issue by jiezhangGt** [airaria/TextBrewer#2]
你好，请问TextBrewer可用于机器翻译的任务中吗？

**Comment by airaria** [comment]
你好， 从任务类型上来说可以做seq2seq任务的蒸馏，不过TextBrewer尚未针对这类任务做特别的优化与文档说明。
你可以自己先行尝试，或者等待我们后续更新。

**Comment by jiezhangGt** [comment]
> 你好， 从任务类型上来说可以做seq2seq任务的蒸馏，不过TextBrewer尚未针对这类任务做特别的优化与文档说明。
> 你可以自己先行尝试，或者等待我们后续更新。

好的，感谢。我自己做过NMT的知识蒸馏，不过一直没有收益。所以想看看你们的方法是不是能做work。

**Comment by AIikai** [comment]
> > 你好， 从任务类型上来说可以做seq2seq任务的蒸馏，不过TextBrewer尚未针对这类任务做特别的优化与文档说明。
> > 你可以自己先行尝试，或者等待我们后续更新。
> 
> 好的，感谢。我自己做过NMT的知识蒸馏，不过一直没有收益。所以想看看你们的方法是不是能做work。

您好，请问针对NMT的知识蒸馏，有什么建议吗？自己尝试过比较简单的序列知识蒸馏，损失不小，想对比一下其它的蒸馏方法
