### ISSUE TITLE
SQuAD上的实验代码可以展示一下吗

### ISSUE THREAD

**Issue by YYangZiXin** [airaria/TextBrewer#20]

**Comment by airaria** [comment]
你好，谢谢关注！
我们会考虑在下次更新中添加SQuAD上的实验代码。
因为除了语言不同，SQuAD和CMRC2018的任务设置和形式都是一致的，目前你可以在CMRC2018代码的基础上做调整以适配SQuAD。超参的设置在[论文](https://www.aclweb.org/anthology/2020.acl-demos.2/)中也有相应说明。

**Comment by YYangZiXin** [comment]
请问CMRC2018示例中的fake_file作用是什么，如何获取呢？

**Comment by airaria** [comment]
Hi,
fake_file用于数据增强，在CMRC2018上你可以使用DRCD阅读理解数据集作为fake_file。
若在SQuAD 2.0 上做数据增强，方法可以参考[这篇论文](https://arxiv.org/abs/1911.03614)的Appendices中的方法构造一些伪数据。

Thanks.

**Comment by YYangZiXin** [comment]
非常感谢
