### ISSUE TITLE
命名`temperature_scheduler`的合理性

### ISSUE THREAD

**Issue by shenfe** [airaria/TextBrewer#24]
如题。

scheduler一般需要某个或某些值随训练过程而变化，但temperature_scheduler并没有，而只是每次临时计算的值，影响kd_loss的计算，并没有被记录下来或影响下一batch。

因此我觉得命名为scheduler不妥当，有误导，其实是和loss一样作为function。

**Comment by airaria** [comment]
您好，
感谢您的建议，我们会考虑在之后的版本更换为一个更合适的名字。如果您有什么建议(temperature_function?)，欢迎提出。
为了保证兼容性，现在的名字也会保留。
