### ISSUE TITLE
What is CustomMatch?

### ISSUE THREAD

**Issue by zhujiangang** [airaria/TextBrewer#25]
I found this parameter in the API, can you please explain what is this and when to use it? Is it something similar as IntermediateMatch? Thanks.

**Comment by airaria** [comment]
**It is untested, you can safely ignore it : )**
--------------
The purpose of CustomMatch is to let you directly match the layers of teacher and student, without changing the code.

For example, if you want to match the outputs of "value" layer in the BertSelfAttention using IntermediateMatch, you have to return the outputs all the way up through the nested modules (BertSelfAttention->BertAttention->BertLayer->BertEncoder->BertModel) and modify the BERT code. The work is annoying. By using CustomMatch, you could simply add the matching by refer the layer to be matched as `BertModel.encoder.layer[i].attention.self.value`.
