### ISSUE TITLE
蒸馏的时候映射层的对应关系是什么样的

### ISSUE THREAD

**Issue by 652994331** [airaria/TextBrewer#35]
非常棒的工具，感谢您的开发。近期 用您的工具 蒸馏一个 electra-base 模型到 electra-small. 级别，蒸馏20轮准确率上出现了下降约1.8%左右的问题， 我在教师模型 和学生模型映射层对应的时候 使用的是 0-0 8-8 12-12 这样的对应关系（因为考虑到electra-base electra-small 都是12层模型）。请问这样的做法会导致问题的产生吗。此外 之前 hugging face 对于 bert 模型的蒸馏12 层-6层我记得他经过了很多实验，找到了一些映射层对应的策略（教师的第几层 对应学生的第几层），我的问题是 假如我也想蒸馏一个electra-base 6层学生模型 这类的映射层对应有没有可以参考的实验记录呢 谢谢您

**Comment by airaria** [comment]
我这边12层到12层的效果可以参见
[https://textbrewer.readthedocs.io/en/latest/Experiments.html](https://textbrewer.readthedocs.io/en/latest/Experiments.html)
页面上的T12-nano(英文BERT)和electra-small(中文electra) 相关结果。
使用的match是 examples/matches/matches.py  中的small_hidden_smmd和small_hidden_mse。

最近有篇论文（[Improving Task-Agnostic BERT Distillation with Layer Mapping Search](https://arxiv.org/abs/2012.06153)）搜索了各种层对应策略，你可以参考下。

**Comment by 652994331** [comment]
@airaria 感谢您的回复

**Comment by sxthunder** [comment]
请问您蒸馏的是什么任务啊？可以交流一下吗？
