### ISSUE TITLE
关于MMD loss

### ISSUE THREAD

**Issue by sz128** [airaria/TextBrewer#36]
https://github.com/airaria/TextBrewer/blob/6c9a21bec34541ed1814623843016d170a912d36/src/textbrewer/losses.py#L267-L269

如上，bmm计算了同一句话的隐层向量相关度后，为什么除的是 .size(1) （即句子长度），但是 mask==None的时候除的又是 .size(2):
https://github.com/airaria/TextBrewer/blob/6c9a21bec34541ed1814623843016d170a912d36/src/textbrewer/losses.py#L261-L262

哪一种是正确的？

**Comment by airaria** [comment]
你好， 感谢你的反馈！
这里应该都除以.size(2)。
代码中的不一致我们会尽快修复。

**Comment by sz128** [comment]
不客气。

另外，作为一个探讨，借鉴Transformer self-attention的做法，是不是除以math.sqrt(state.size(2)) 会更合理？

**Comment by airaria** [comment]
这里除以 .size(2) 是参考了[A Gift from Knowledge Distillation](https://openaccess.thecvf.com/content_cvpr_2017/papers/Yim_A_Gift_From_CVPR_2017_paper.pdf) 中的Eq (1)（那里的FSP matrix的形状是hidden * hidden，除以长度；这里相似度矩阵的形状是len * len，所以除以hidden）。

我觉得除以math.sqrt(state.size(2))也可以一试，大致相当于损失的权重放大约30倍(1/768 -> 1/28，1/1024 -> 1/32)。
我在实验中并没有仔细调过权重，所以效果并不清楚。欢迎自行尝试😀
