### ISSUE TITLE
TypeError: model should be either torch.nn.Module or a dict

### ISSUE THREAD

**Issue by dakota987** [airaria/TextBrewer#38]
TypeError: model should be either torch.nn.Module or a dict
And how to load dataloader, optimizer and all.
If anyone could share a colab note book it would be of great help.

**Comment by airaria** [comment]
Can you paste your code and describe your question in detail?



You could refer to the examples in the examples directory for the moment.















At 2021-01-14 16:59:07, "dakota987" <notifications@github.com> wrote:

TypeError: model should be either torch.nn.Module or a dict
And how to load dataloader, optimizer and all.
If anyone could share a colab note book it would be of great help.
