### ISSUE TITLE
mnli_example实验相关

### ISSUE THREAD

**Issue by qq260612718** [airaria/TextBrewer#41]
您好，请问mnli_example这个实验环境是多少？如：pytorch和transformers等。
在多次尝试运行时都会出现以下问题：
2021/02/03 16:54:38 - INFO - utils -  Loading features from cached file data_root_dir/SST2/cached_train_128_sst-2
2021/02/03 16:54:39 - INFO - utils -  Loading features from cached file data_root_dir/SST2/cached_dev_128_sst-2
2021/02/03 16:54:39 - INFO - Main -  Data loaded
Traceback (most recent call last):
  File "main.trainer.py", line 220, in <module>
    main()
  File "main.trainer.py", line 160, in main
    assert len(missing_keys)==0
AssertionError

**Comment by airaria** [comment]
并没有使用transformer，用的是其原先版本pytorch_pretrained_bert，也在mnli_example目录下。
可能是权重问题，
你把assert len(missing_keys)==0 改成 assert len(missing_keys)==0,missing_keys，看下到底是什么权重没匹配上













在 2021-02-03 16:57:43，"qq260612718" <notifications@github.com> 写道：

您好，请问mnli_example这个实验环境是多少？如：pytorch和transformers等。
在多次尝试运行时都会出现以下问题：
2021/02/03 16:54:38 - INFO - utils - Loading features from cached file data_root_dir/SST2/cached_train_128_sst-2
2021/02/03 16:54:39 - INFO - utils - Loading features from cached file data_root_dir/SST2/cached_dev_128_sst-2
2021/02/03 16:54:39 - INFO - Main - Data loaded
Traceback (most recent call last):
File "main.trainer.py", line 220, in
main()
File "main.trainer.py", line 160, in main
assert len(missing_keys)==0
AssertionError

**Comment by qq260612718** [comment]
谢谢，原始实验模型已经可以运行了。我想将您该mnli_example实验所用到的**BERT-Base, Cased: 12-layer, 768-hidden, 12-heads , 110M parameters,**替换成**BERT-Base, Multilingual Cased (New, recommended): 104 languages, 12-layer, 768-hidden, 12-heads, 110M parameters**尝试运行，但所有权重似乎都不能匹配上，我检查了两个模型bert_config基本相同，请问该预训练模型可以修改替換吗？

**Comment by airaria** [comment]
如果匹配不上，你print一下bert-base模型和multilingual bert模型的权重(state_dict)的key，它们应该是一样的，看看是不是这里不同？










在 2021-02-18 17:37:56，"qq260612718" <notifications@github.com> 写道：

谢谢，原始实验模型已经可以运行了。我想将您该mnli_example实验所用到的BERT-Base, Cased: 12-layer, 768-hidden, 12-heads , 110M parameters,替换成BERT-Base, Multilingual Cased (New, recommended): 104 languages, 12-layer, 768-hidden, 12-heads, 110M parameters尝试运行，但所有权重似乎都不能匹配上，我检查了两个模型bert_config基本相同，请问该预训练模型可以修改替換吗？

**Comment by Soulscb** [comment]
> 谢谢，原始实验模型已经可以运行了。我想将您该mnli_example实验所用到的**BERT-Base, Cased: 12-layer, 768-hidden, 12-heads , 110M parameters,**替换成**BERT-Base, Multilingual Cased (New, recommended): 104 languages, 12-layer, 768-hidden, 12-heads, 110M parameters**尝试运行，但所有权重似乎都不能匹配上，我检查了两个模型bert_config基本相同，请问该预训练模型可以修改替換吗？

请问你是怎么运行起来的呀？我最近也遇到这个问题了，尝试了各种方法都没运行起来
