### ISSUE TITLE
请问一下msra实体识别任务中，matches没有给参数，默认是用那种蒸馏方式啊？

### ISSUE THREAD

**Issue by SunyanGu** [airaria/TextBrewer#45]

**Comment by airaria** [comment]
MSRA NER任务上从Electra-base蒸馏的ELectra-small的实验中，使不使用matches的效果差别不大，所以在实验结果和例子中我们展现的都是不使用matches的设置。
















在 2021-02-23 10:08:25，"顾孙炎" <notifications@github.com> 写道：
