### ISSUE TITLE
msra命名实体识别任务无法复现结果

### ISSUE THREAD

**Issue by houpanpan** [airaria/TextBrewer#49]
您好，msra命名实体识别任务中，teacher模型的train过程无法复现结果啊，运行多次，变化不同的epoches，f1结果最高才79.54%啊，是我哪里的参数设置错误了嘛

**Comment by another1s** [comment]
@houpanpan teacher model本质上只是fine-tune了一遍吧，按道理不可能有问题的？你看看具体哪种标签预测错误较多

**Comment by airaria** [comment]
直接运行ner_ElectraTrain_dist.sh，在半个epoch F1可以达到90以上。你再检查下数据或模型是不是有问题？

**Comment by MrRace** [comment]
@airaria 我这边蒸馏的模型，F1只有 F1: 74.980，训练和蒸馏都是使用官方的默认参数，这与官方的结果差距很大。

**Comment by airaria** [comment]
> @airaria 我这边蒸馏的模型，F1只有 F1: 74.980，训练和蒸馏都是使用官方的默认参数，这与官方的结果差距很大。

teacher效果多少？
student是什么结构？是直接运行[ner_ElectraDistill_dist.sh](https://github.com/airaria/TextBrewer/blob/master/examples/msra_ner_example/ner_ElectraDistill_dist.sh)吗

**Comment by MrRace** [comment]
@airaria 
训练阶段，模型使用 `chinese-electra-base-discriminator` : `https://huggingface.co/hfl/chinese-electra-base-discriminator`,
蒸馏阶段，student模型使用`chinese-electra-small-discriminator`:  `https://huggingface.co/hfl/chinese-electra-small-discriminator` 进行初始化。

是直接运行[ner_ElectraDistill_dist.sh](https://github.com/airaria/TextBrewer/blob/master/examples/msra_ner_example/ner_ElectraDistill_dist.sh)。

训练阶段 `output_dir/eval_results.txt` 结果如下：
```
Step: 1875
F1: 92.129
P: 91.131
Acc: 99.098Step: 3750
F1: 93.523
P: 92.817
Acc: 99.204Step: 5625
F1: 94.571
P: 94.423
Acc: 99.338Step: 7500
F1: 94.904
P: 94.393

```

**Comment by MrRace** [comment]
@airaria 

> @airaria 我这边蒸馏的模型，F1只有 F1: 74.980，训练和蒸馏都是使用官方的默认参数，这与官方的结果差距很大。

@airaria 请问是我哪里设置有问题吗？

**Comment by MrRace** [comment]
@airaria 求下复现使用的预训练模型的具体链接？尚未复现成功

**Comment by airaria** [comment]
> @airaria 求下复现使用的预训练模型的具体链接？尚未复现成功

Transformers版本是多少？可否降到3.X的版本试试？
另外，请贴一下蒸馏实验日志的前200行，以及蒸馏实验的eval_results.txt的内容。

**Comment by MrRace** [comment]
> > @airaria 求下复现使用的预训练模型的具体链接？尚未复现成功
> 
> Transformers版本是多少？可否降到3.X的版本试试？ 另外，请贴一下蒸馏实验日志的前200行，以及蒸馏实验的eval_results.txt的内容。

@airaria 尝试将 [ner_ElectraDistill_dist.sh](https://github.com/airaria/TextBrewer/blob/master/examples/msra_ner_example/ner_ElectraDistill_dist.sh) learning rate 改为lr=1e-4，epoch=60，能够显著改善：
```
Acc: 98.532Step: 225000
F1: 87.019
P: 87.465
```
但是距离官方公布的结果还是有很大差距。
具体：
[eval_results.txt](https://github.com/airaria/TextBrewer/files/11671897/eval_results.txt)

**Comment by MrRace** [comment]
@airaria msra ner 这个任务希望官方能够重新复现下，包括具体的预训练模型和超参数。查看多个issues [issues/57](https://github.com/airaria/TextBrewer/issues/57)、[issues/49](https://github.com/airaria/TextBrewer/issues/49)、[issues/48](https://github.com/airaria/TextBrewer/issues/48) 发现仍然有多人无法复现 msra ner 这个任务。

**Comment by iyorke** [comment]
我复现了一下这个任务，用的Teacher model和Student model分别是Chinese-ELECTRA-base和Chinese-ELECTRA-small；实验超参设置和examples/msra_ner_example里的ner_ElectraTrain_dist.sh、ner_ElectraDistill_dist.sh保持了一致。

我这里F1上实验结果没有太大问题，可以达到Teacher：95.50，Student：93.68
（我在TeslaV100-16G上进行测试，环境为Pytorch==1.10.0，Transformers==4.28.0）
