### ISSUE TITLE
直接运行ner_ElectraTrain_dist.sh，在半个epoch F1可以达到90以上。你再检查下数据或模型是不是有问题？

### ISSUE THREAD

**Issue by houpanpan** [airaria/TextBrewer#52]
直接运行ner_ElectraTrain_dist.sh，在半个epoch F1可以达到90以上。你再检查下数据或模型是不是有问题？

_Originally posted by @airaria in https://github.com/airaria/TextBrewer/issues/49#issuecomment-796336893_

**Comment by houpanpan** [comment]
在ElectraTrain base模型是可以复现结果的，但是把教师模型改为bert模型，为啥finetune的结果非常差呢，是需要改哪些参数嘛

**Comment by airaria** [comment]
中文Electra的学习率较大。用bert时你把学习率调小到3e-5、2e-5试试
















在 2021-03-22 08:43:23，"houpanpan" ***@***.***> 写道：

在ElectraTrain base模型是可以复现结果的，但是把教师模型改为bert模型，为啥finetune的结果非常差呢，是需要改哪些参数嘛

**Comment by houpanpan** [comment]
前辈您好，NER任务的finetune过程，我将模型改为bert-base后，学习率改为2e-5/3e-5，衰减系数为1，反复试验多次，结果均很差很差，是我哪里设置出了问题嘛，按理说F1结果应该在90%才对啊，求指导，谢谢。
