### ISSUE TITLE
更换模型无法复现finetune结果

### ISSUE THREAD

**Issue by houpanpan** [airaria/TextBrewer#53]
前辈您好，NER任务的finetune过程，我将模型改为bert-base后，学习率改为2e-5/3e-5，衰减系数为1，反复试验多次，结果均很差很差，是我哪里设置出了问题嘛，按理说F1结果应该在90%才对啊，求指导，谢谢。

**Comment by MrRace** [comment]
按照官方的方式，同样无法复现
