### ISSUE TITLE
运行时错误，询问。

### ISSUE THREAD

**Issue by Noeverer** [airaria/TextBrewer#59]
运行run_cmrc2018_distill_T3.sh 出现错误，想询问是什么原因？

0it [00:00, ?it/s]
  0% 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.distill.py", line 212, in <module>
    main()
  File "main.distill.py", line 202, in main
    num_epochs=args.num_train_epochs, callback=callback_func)
  File "/usr/local/lib/python3.7/dist-packages/textbrewer/distiller_basic.py", line 283, in train
    self.train_with_num_epochs(optimizer, scheduler, tqdm_disable, dataloader, max_grad_norm, num_epochs, callback, batch_postprocessor, **args)
  File "/usr/local/lib/python3.7/dist-packages/textbrewer/distiller_basic.py", line 212, in train_with_num_epochs
    total_loss, losses_dict = self.train_on_batch(batch,args)
  File "/usr/local/lib/python3.7/dist-packages/textbrewer/distiller_general.py", line 79, in train_on_batch
    total_loss, losses_dict = self.compute_loss(results_S, results_T)
  File "/usr/local/lib/python3.7/dist-packages/textbrewer/distiller_general.py", line 141, in compute_loss
    inter_T = inters_T[feature][layer_T]
IndexError: list index out of range

运行的脚本：
python -u main.distill.py \
    --vocab_file $BERT_DIR/vocab.txt \
    --do_lower_case \
    --bert_config_file_T $STUDENT_CONF_DIR/bert_config.json \
    --bert_config_file_S $STUDENT_CONF_DIR/bert_config_L3.json \
    --tuned_checkpoint_T $trained_teacher_model \
    --init_checkpoint_S $BERT_DIR/pytorch_model.bin \
    --do_train \
    --do_eval \
    --do_predict \
    --doc_stride 128 \
    --max_seq_length ${length} \
    --train_batch_size ${batch_size} \
    --random_seed $torch_seed \
    --train_file $cmrc_train_file \
    --fake_file_1 $DA_file \
    --predict_file $cmrc_dev_file \
    --num_train_epochs ${ep} \
    --learning_rate ${lr}e-5 \
    --ckpt_frequency 1 \
    --schedule slanted_triangular \
    --s_opt1 ${sopt1} \
    --output_dir $OUTPUT_DIR \
    --gradient_accumulation_steps ${accu} \
    --temperature ${temperature} \
    --output_att_score true \
    --output_att_sum false  \
    --output_encoded_layers true \
    --output_attention_layers true \
    --matches L3_hidden_mse \
              L3_hidden_smmd \
    --tag RB \

**Comment by airaria** [comment]
```python
inter_T = inters_T[feature][layer_T]
IndexError: list index out of range
```
从这句看是无法从teacher的输出中找到指定的层，teacher没有返回足够长的feature的list, layer_T的大小超过了list长度
代码上做了哪些更改？
