### ISSUE TITLE
请问下在mnli任务训练中，第一步训练的是教师模型，配置为啥加载的是学生模型的配置？

### ISSUE THREAD

**Issue by binglinchengxiash** [airaria/TextBrewer#61]
![image](https://user-images.githubusercontent.com/15050040/114512513-c6762f80-9c6b-11eb-8c29-d4425ef79823.png)

**Comment by ZHEGG** [comment]
+1

**Comment by airaria** [comment]
> +1

因Fine-tune中不区分student和teacher，
此处student的配置即为teacher的配置
