### ISSUE TITLE
维度不匹配问题

### ISSUE THREAD

**Issue by iamxinxin** [airaria/TextBrewer#63]
我用参照快速开始的代码 想要蒸馏一个finetune过的多分类模型，data也是参照example里的方式组织的，但是遇到一个 word embedding和position embedding维度不匹配的问题。没搞明白为什么出现这样的问题，请问有啥建议呀？
错误定位：
transformers/models/bert/modeling_bert.py", line 207, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (500) must match the size of tensor b (64) at non-singleton dimension 1
![image](https://user-images.githubusercontent.com/37991379/114969957-04619680-9eac-11eb-9b06-1295ecd5d2e0.png)
![image](https://user-images.githubusercontent.com/37991379/114970031-2d822700-9eac-11eb-990f-b13f6634e38e.png)

**Comment by YoungErm** [comment]
你好，请问你是怎么解决这个问题的
