### ISSUE TITLE
Type Error: __init__() got an unexpected keyword argument 'unk_token'

### ISSUE THREAD

**Issue by SnailDM** [airaria/TextBrewer#65]
when I use the distilled bert model, tokenizer=cls(*init_inputs, **init_kwargs)   Type Error: __init__() got an unexpected keyword argument 'unk_token'。

我训练完蒸馏模型后，调用这个蒸馏模型进行预测时会报错，用的是conll2003_example中的run_ner_distill.py，报错：/transformers/tokenization_utils.py, line 282, in from_pretrained return cls._from_pretrained(*inputs, **kwargs)
tokenizer = cls(*init_inputs, **init_kwargs)
Type Error: __init__() got an unexpected keyword argument 'unk_token'

**Comment by airaria** [comment]
你用的Transformer版本是多少？
你可以用 Transformers 3.0.2 看还报不报错，确认是否是Transformers问题

**Comment by SnailDM** [comment]
> 你用的Transformer版本是多少？
> 你可以用 Transformers 3.0.2 看还报不报错，确认是否是Transformers问题

好的，我试试。谢谢了~
