### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by liuhl-source** [airaria/TextBrewer#66]
Thanks for your great work!  Can you give a guide about data preparation, such as MNLI.  The files you mentioned are not the same as the data I downloaded(https://cims.nyu.edu/~sbowman/multinli/). Thanks for your help.

**Comment by liuhl-source** [comment]
I unzip the multinli_1.0.zip, then it gives:
Icon                            
multinli_1.0_dev_mismatched.jsonl  
multinli_1.0_train.txt
multinli_1.0_dev_matched.jsonl  
multinli_1.0_dev_mismatched.txt    
paper.pdf
multinli_1.0_dev_matched.txt    
multinli_1.0_train.jsonl          
README.txt

**Comment by airaria** [comment]
I use the MNLI dataset from GLUE benchmark, you can download it here https://github.com/nyu-mll/GLUE-baselines













At 2021-05-18 16:14:21, "liuhl" ***@***.***> wrote:

I unzip the multinli_1.0.zip, then it gives:
Icon
multinli_1.0_dev_mismatched.jsonl
multinli_1.0_train.txt
multinli_1.0_dev_matched.jsonl
multinli_1.0_dev_mismatched.txt
paper.pdf
multinli_1.0_dev_matched.txt
multinli_1.0_train.jsonl
README.txt
