### ISSUE TITLE
关于中文阅读理解数据集t4学生模型蒸馏配置的问题

### ISSUE THREAD

**Issue by SouthBays** [airaria/TextBrewer#68]
你好，
感谢优秀的框架，当前已经跑通cmrc2018， train过程f1能达到86和理论值接近，但是
用上述教师模型蒸馏t4学生模型时一开始只有30的f1值，后来加了weight_decay_rate=0.0后能达到65的f1值，一般运行10个epoch左右就无法再提升了，跟理论值还是有较大差距,是不是优化器和学习率的配置的问题？
当前参数
text_brewer=0.2.1
transformer=3.4.0
train主要配置：
accu=1
ep=2
lr=3
batch_size=16
length=512
doc_stride=320
s_opt1=30
distill配置:
accu=1
ep=30
lr=10
temperature=8
batch_size=20
length=512
sopt1=1 
weight_decay_rate 0.0

**Comment by airaria** [comment]
num_train_epochs 设置成50试试？
另外 --matches 设置了 L4t_hidden_mse 和 L4_hidden_smmd 吗

**Comment by SouthBays** [comment]
matches参数是有的，epochs 50也跑满了一次，f1到60多的时候就一直往下降了。
![image](https://user-images.githubusercontent.com/31915490/121201067-d21a5700-c8a6-11eb-942d-a82bfdba1db7.png)

**Comment by airaria** [comment]
是否是直接运行的 run_cmrc2018_distill_T4tiny.sh 呢？直接运行脚本蒸馏结果F1可以到83。
是否做了某些改动？
