### ISSUE TITLE
模型没有被训练，每个epoch保存的模型weight一模一样。

### ISSUE THREAD

**Issue by Jay2Coomzz** [airaria/TextBrewer#70]
使用了simCSE算法训练了计算相似度的模型，12层BERT，想要将其蒸馏为4层的BERT。共训练40个epoch，发现student模型效果和没有训练一样。首先查看了loss，发现没有什么问题，如下图。
![微信图片_20210621091340](https://user-images.githubusercontent.com/41030911/122694908-8043da80-d271-11eb-878e-aebb6b3cd87e.png)
又查看了一下第1个、20个、40个模型的权重，发现完全一样，如下图。
第1个：
![微信图片_20210621091158](https://user-images.githubusercontent.com/41030911/122695240-6f479900-d272-11eb-8430-e0c1e9db94c5.png)
第20个：
![微信图片_20210621091154](https://user-images.githubusercontent.com/41030911/122695267-7c648800-d272-11eb-861d-380e3d505087.png)
第40个：
![微信图片_20210621091148](https://user-images.githubusercontent.com/41030911/122695276-81293c00-d272-11eb-8b52-71670322f087.png)

请问是保存模型的方法有问题吗，我使用的方法如下。
train_config = TrainingConfig(
            gradient_accumulation_steps = 1,
            ckpt_frequency = 2,
            log_dir = output_dir,
            output_dir = output_dir,
            device = device)

**Comment by airaria** [comment]
用的是单机单卡训练吗
















在 2021-06-21 09:25:12，"Jay2Coomzz" ***@***.***> 写道：

使用了simCSE算法训练了计算相似度的模型，12层BERT，想要将其蒸馏为4层的BERT。共训练40个epoch，发现student模型效果和没有训练一样。首先查看了loss，发现没有什么问题，如下图。

又查看了一下第1个、20个、40个模型的权重，发现完全一样，如下图。
第1个：

第20个：

第40个：


请问是保存模型的方法有问题吗，我使用的方法如下。
train_config = TrainingConfig(
gradient_accumulation_steps = 1,
ckpt_frequency = 2,
log_dir = output_dir,
output_dir = output_dir,
device = device)

**Comment by Jay2Coomzz** [comment]
> 用的是单机单卡训练吗 在 2021-06-21 09:25:12，"Jay2Coomzz" ***@***.***> 写道： 使用了simCSE算法训练了计算相似度的模型，12层BERT，想要将其蒸馏为4层的BERT。共训练40个epoch，发现student模型效果和没有训练一样。首先查看了loss，发现没有什么问题，如下图。 又查看了一下第1个、20个、40个模型的权重，发现完全一样，如下图。 第1个： 第20个： 第40个： 请问是保存模型的方法有问题吗，我使用的方法如下。 train_config = TrainingConfig( gradient_accumulation_steps = 1, ckpt_frequency = 2, log_dir = output_dir, output_dir = output_dir, device = device) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的

**Comment by rucieryi369** [comment]
请问您是怎么解决这个问题的呢？
