### ISSUE TITLE
使用自定义的网络结构

### ISSUE THREAD

**Issue by zhangatao** [airaria/TextBrewer#76]
你好，首先感谢你们开源这么好的项目。我这块有两个问题要请教：
1，能不能基于你们的框架使用自定义的网络结构，比如中文的ner任务，我自己定义了双指针的结构，不使用transformers自带的基于token级别的分类，如果可以的话，是不是重写BertForTokenClassification这个类就行？
2，我使用你们开源的方法蒸馏了一个模型，然后我还可以在这个基础上，使用自己定义的网络结构，进行进一步的finetune吗，有没有这个必要。
🙏

**Comment by airaria** [comment]
1. 使用任何网络结构都可以，也不必继承或重写Transformers的BertForTokenClassification，只要是继承自torch.nn.Module就可以
2. 一般蒸馏之后就没有fine-tune的必要了，可能反而会引起效果下降。当然一切以实验为准
在2021年07月14日 ***@***.***> 写道：

你好，首先感谢你们开源这么好的项目。我这块有两个问题要请教：
1，能不能基于你们的框架使用自定义的网络结构，比如中文的ner任务，我自己定义了双指针的结构，不使用transformers自带的基于token级别的分类，如果可以的话，是不是重写BertForTokenClassification这个类就行？
2，我使用你们开源的方法蒸馏了一个模型，然后我还可以在这个基础上，使用自己定义的网络结构，进行进一步的finetune吗，有没有这个必要。
🙏

**Comment by zhangatao** [comment]
好的，谢谢
